version: '3'
networks:
  rede:
    # Use a custom driver
    driver: bridge
services:
  mongo_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: felipe
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: